export interface TeamMember {
  id: string;
  name: string;
  designation: string;
  discipline: string;
  courseFocus: string;
  levelFocus: string;
  trackOwned: string;
  isAcademicFaculty?: boolean;
}

export interface CoordinationLevel {
  number: number;
  title: string;
  semesterId: string;
  semesterTitle: string;
  semesterFocus: string;
  lead: string;
  mentors: string[];
  certifications: string;
}

export interface CourseCoordinationItem {
  code: string;
  title: string;
  academic: string;
  mentors: string[];
  note?: string;
}

export const TEAM_ROSTER: TeamMember[] = [
  {
    id: "sridas-d",
    name: "Sridas D",
    designation: "Software Solution Architect",
    discipline: "Solution Architecture",
    courseFocus: "CS101 & CS102 Architecture",
    levelFocus: "L2, L5, L9, L11, L18, L20",
    trackOwned: "Architecture reviews, blueprint sign-off & AI/cloud solution design",
  },
  {
    id: "arun-kumar-balakrishnan",
    name: "Arun Kumar Balakrishnan",
    designation: "Senior Project Manager - Enterprise Systems",
    discipline: "Programme Governance",
    courseFocus: "Process & CS501 Governance",
    levelFocus: "L10, L15, L16, L19, L20",
    trackOwned: "CMMI Associate, documentation, programme governance & industry evaluation",
  },
  {
    id: "soorya-krishnan-g",
    name: "Soorya Krishnan G",
    designation: "Software Project Manager, CDIPD",
    discipline: "Agile and Sprint Cadence",
    courseFocus: "Weekly sprints across the programme",
    levelFocus: "L1, L17 (All levels cadence)",
    trackOwned: "Agile Scrum, Certified Scrum Master & delivery cadence",
  },
  {
    id: "krishnasree-k",
    name: "Krishnasree K",
    designation: "Team Lead - Java; Project Manager",
    discipline: "Backend, Java & Delivery Management",
    courseFocus: "CS104 and Delivery",
    levelFocus: "L9, L12, L17",
    trackOwned: "API, microservices, sprint management and delivery management",
  },
  {
    id: "vyga-v-r",
    name: "Vyga V R",
    designation: "Senior Business Analyst",
    discipline: "Requirements and Research",
    courseFocus: "Research and Product",
    levelFocus: "L1, L3, L16, L19",
    trackOwned: "Market and user research, feasibility analysis & industry liaison",
  },
  {
    id: "smitha-surendran",
    name: "Smitha Surendran",
    designation: "Manager - HR",
    discipline: "Programme Administration & Student Success",
    courseFocus: "Non-academic support & Placement",
    levelFocus: "L1, L16, L19",
    trackOwned: "Student success, programme operations & industry placement",
  },
  {
    id: "anoop-raj-r-v",
    name: "Anoop Raj R V",
    designation: "Technical Lead - Database Systems",
    discipline: "Data and Database Engineering",
    courseFocus: "CS103; CS1101 elective",
    levelFocus: "L6, L7, L13",
    trackOwned: "MongoDB, Google Professional Data Engineer and big data (Spark / Flink)",
  },
  {
    id: "nidheesh-g",
    name: "Nidheesh G",
    designation: "Database Administrator",
    discipline: "Database Administration & Data Governance",
    courseFocus: "CS103 and CS501 Governance",
    levelFocus: "L6, L14",
    trackOwned: "Database administration, PostgreSQL/storage performance & data privacy",
  },
  {
    id: "arun-nadh-g",
    name: "Arun Nadh G",
    designation: "Senior Architect - Cloud, Infrastructure and DevOps",
    discipline: "Cloud, Infrastructure & DevOps",
    courseFocus: "CS105 DevOps; CS102 Cloud; CS101 Deployment",
    levelFocus: "L4, L7, L10, L12, L13, L14, L15, L20",
    trackOwned: "AWS CLF, AWS SAA, AWS DOP, GCP ACE, CKA, Docker and GitHub Actions",
  },
  {
    id: "abhi-krishnan-r",
    name: "Abhi Krishnan R",
    designation: "Lead UI/UX Developer-1",
    discipline: "UI/UX and Product Design",
    courseFocus: "CS102 Frontend & CS601",
    levelFocus: "L3, L4, L5",
    trackOwned: "UI/UX, Figma design systems, frontend architecture",
  },
  {
    id: "prasanth-lal-s-n",
    name: "Prasanth Lal S N",
    designation: "Senior Front End Developer",
    discipline: "UI and Frontend Development",
    courseFocus: "CS102; CS601 elective",
    levelFocus: "L4, L5, L9",
    trackOwned: "Frontend engineering, React and Next.js frameworks",
  },
  {
    id: "maneesh-george-johnson",
    name: "Maneesh George Johnson",
    designation: "Senior Front End Developer",
    discipline: "UI and Frontend Development",
    courseFocus: "CS102; CS601 elective",
    levelFocus: "L5, L17",
    trackOwned: "React, Next.js and advanced frontend frameworks",
  },
  {
    id: "ajitha-v-s",
    name: "Ajitha V S",
    designation: "Technical Lead - QA and Testing; Project Manager",
    discipline: "Quality Assurance and Test Automation",
    courseFocus: "CS105 and Quality",
    levelFocus: "L8, L9, L15",
    trackOwned: "Test automation, CI/CD testing and QA sign-off",
  },
  {
    id: "soorya-s-kumar",
    name: "Soorya S Kumar",
    designation: "Team Lead - Java, Product Development Center",
    discipline: "Backend and Java",
    courseFocus: "CS103 and CS104",
    levelFocus: "L6, L8, L11, L17",
    trackOwned: "Postman API, API testing, and backend engineering",
  },
  {
    id: "diju-m",
    name: "Diju M",
    designation: "Senior Software Engineer - Java",
    discipline: "Backend and Code Review",
    courseFocus: "Sprint Builds and Microservices",
    levelFocus: "L8, L12, L18",
    trackOwned: "Peer review, backend implementation and code-review facilitation",
  },
  {
    id: "bibin-babu",
    name: "Bibin Babu",
    designation: "Senior Software Engineer - Mobile Apps",
    discipline: "Mobile and Cross-Platform Frontend",
    courseFocus: "CS102 Mobile & CS601 Mobile",
    levelFocus: "L5, L17, L18",
    trackOwned: "React Native, cross-platform mobile build & UI execution",
  },
  {
    id: "dr-manoj-kumar",
    name: "Dr Manoj Kumar",
    designation: "Academic Faculty & Programme Head",
    discipline: "AI, Machine Learning & Academic Evaluation",
    courseFocus: "CS101 (AI & ML), CS501 (AI Ethics), CS1101 (Big Data)",
    levelFocus: "Academic oversight across Semesters I–IV",
    trackOwned: "Academic syllabus approval, credit evaluation, and formal grading",
    isAcademicFaculty: true,
  },
  {
    id: "dr-ajith-kumar",
    name: "Dr Ajith Kumar",
    designation: "Academic Faculty & Curriculum Lead",
    discipline: "Software Architecture, Full Stack & Frontend",
    courseFocus: "CS102 (Full Stack), CS501 (Ethics), CS601 (Advanced Frontend)",
    levelFocus: "Academic oversight across Semesters I–IV",
    trackOwned: "Academic syllabus approval, credit evaluation, and formal grading",
    isAcademicFaculty: true,
  },
];

export const COORDINATION_LEVELS: CoordinationLevel[] = [
  // Semester I
  {
    number: 1,
    title: "Orientation and Foundations",
    semesterId: "S1",
    semesterTitle: "Semester I",
    semesterFocus: "Research, UX, architecture and electives",
    lead: "Vyga V R",
    mentors: ["Soorya Krishnan G", "Smitha Surendran"],
    certifications: "Git and GitHub",
  },
  {
    number: 2,
    title: "AI and Architecture Deep Dive",
    semesterId: "S1",
    semesterTitle: "Semester I",
    semesterFocus: "Research, UX, architecture and electives",
    lead: "Requires confirmation",
    mentors: ["AI/ML SME — GAP", "Sridas D"],
    certifications: "None specified",
  },
  {
    number: 3,
    title: "Electives and Market Research",
    semesterId: "S1",
    semesterTitle: "Semester I",
    semesterFocus: "Research, UX, architecture and electives",
    lead: "Vyga V R",
    mentors: ["Abhi Krishnan R"],
    certifications: "Agile Scrum",
  },
  {
    number: 4,
    title: "Technology Stack, UX and Certification",
    semesterId: "S1",
    semesterTitle: "Semester I",
    semesterFocus: "Research, UX, architecture and electives",
    lead: "Abhi Krishnan R",
    mentors: ["Prasanth Lal S N", "Arun Nadh G"],
    certifications: "AWS CLF; Google UX",
  },
  {
    number: 5,
    title: "Blueprint and Semester I Evaluation",
    semesterId: "S1",
    semesterTitle: "Semester I",
    semesterFocus: "Research, UX, architecture and electives",
    lead: "Sridas D",
    mentors: ["Abhi Krishnan R", "Prasanth Lal S N", "Maneesh George Johnson", "Bibin Babu"],
    certifications: "Meta Front-End",
  },
  // Semester II
  {
    number: 6,
    title: "Backend Foundations and Data",
    semesterId: "S2",
    semesterTitle: "Semester II",
    semesterFocus: "Backend, data, APIs and integration",
    lead: "Anoop Raj R V",
    mentors: ["Soorya S Kumar", "Nidheesh G"],
    certifications: "Docker",
  },
  {
    number: 7,
    title: "AI Model Training and DevOps",
    semesterId: "S2",
    semesterTitle: "Semester II",
    semesterFocus: "Backend, data, APIs and integration",
    lead: "AI/ML SME — GAP",
    mentors: ["Anoop Raj R V", "Arun Nadh G"],
    certifications: "MongoDB; TensorFlow",
  },
  {
    number: 8,
    title: "Electives, APIs and Certification",
    semesterId: "S2",
    semesterTitle: "Semester II",
    semesterFocus: "Backend, data, APIs and integration",
    lead: "Soorya S Kumar",
    mentors: ["Diju M", "Ajitha V S"],
    certifications: "GitHub Actions; Postman",
  },
  {
    number: 9,
    title: "Full-Stack Integration and Testing",
    semesterId: "S2",
    semesterTitle: "Semester II",
    semesterFocus: "Backend, data, APIs and integration",
    lead: "Krishnasree K",
    mentors: ["Sridas D", "Prasanth Lal S N", "Ajitha V S"],
    certifications: "AWS SAA",
  },
  {
    number: 10,
    title: "Local Deployment and Semester II Evaluation",
    semesterId: "S2",
    semesterTitle: "Semester II",
    semesterFocus: "Backend, data, APIs and integration",
    lead: "Arun Nadh G",
    mentors: ["Arun Kumar Balakrishnan"],
    certifications: "None specified",
  },
  // Semester III
  {
    number: 11,
    title: "API Design and Microservices",
    semesterId: "S3",
    semesterTitle: "Semester III",
    semesterFocus: "Microservices, cloud, MLOps and security",
    lead: "Soorya S Kumar",
    mentors: ["Sridas D"],
    certifications: "None specified",
  },
  {
    number: 12,
    title: "Third-Party Integration and Certifications",
    semesterId: "S3",
    semesterTitle: "Semester III",
    semesterFocus: "Microservices, cloud, MLOps and security",
    lead: "Krishnasree K",
    mentors: ["Arun Nadh G", "Diju M"],
    certifications: "CKA; GCP ACE",
  },
  {
    number: 13,
    title: "Cloud Deployment and MLOps",
    semesterId: "S3",
    semesterTitle: "Semester III",
    semesterFocus: "Microservices, cloud, MLOps and security",
    lead: "Arun Nadh G",
    mentors: ["Anoop Raj R V"],
    certifications: "Databricks MLOps",
  },
  {
    number: 14,
    title: "Security, Governance and Live Product",
    semesterId: "S3",
    semesterTitle: "Semester III",
    semesterFocus: "Microservices, cloud, MLOps and security",
    lead: "Arun Nadh G",
    mentors: ["Nidheesh G", "Security SME — GAP"],
    certifications: "CEH",
  },
  {
    number: 15,
    title: "Product Hardening and Semester III Evaluation",
    semesterId: "S3",
    semesterTitle: "Semester III",
    semesterFocus: "Microservices, cloud, MLOps and security",
    lead: "Arun Nadh G",
    mentors: ["Arun Kumar Balakrishnan", "Ajitha V S"],
    certifications: "AWS DevOps Professional",
  },
  // Semester IV
  {
    number: 16,
    title: "Final Project Scoping",
    semesterId: "S4",
    semesterTitle: "Semester IV",
    semesterFocus: "Final product, placement and evaluation",
    lead: "Arun Kumar Balakrishnan",
    mentors: ["Vyga V R", "Smitha Surendran"],
    certifications: "Azure AI-102",
  },
  {
    number: 17,
    title: "Product Build and Certification Sprint",
    semesterId: "S4",
    semesterTitle: "Semester IV",
    semesterFocus: "Final product, placement and evaluation",
    lead: "Soorya Krishnan G",
    mentors: ["Soorya S Kumar", "Krishnasree K", "Maneesh George Johnson", "Bibin Babu"],
    certifications: "Certified Scrum Master",
  },
  {
    number: 18,
    title: "Advanced Features and Expert Review",
    semesterId: "S4",
    semesterTitle: "Semester IV",
    semesterFocus: "Final product, placement and evaluation",
    lead: "Sridas D",
    mentors: ["Diju M", "Bibin Babu"],
    certifications: "AWS Machine Learning Specialty",
  },
  {
    number: 19,
    title: "Report and Industry Evaluation",
    semesterId: "S4",
    semesterTitle: "Semester IV",
    semesterFocus: "Final product, placement and evaluation",
    lead: "Arun Kumar Balakrishnan",
    mentors: ["Vyga V R", "Smitha Surendran"],
    certifications: "Google Professional Data Engineer",
  },
  {
    number: 20,
    title: "Final Viva and Convocation",
    semesterId: "S4",
    semesterTitle: "Semester IV",
    semesterFocus: "Final product, placement and evaluation",
    lead: "Arun Kumar Balakrishnan",
    mentors: ["Sridas D", "Arun Nadh G"],
    certifications: "CMMI Associate",
  },
];

export const COURSE_COORDINATION_MAP: Record<string, CourseCoordinationItem> = {
  CS101: {
    code: "CS101",
    title: "Advanced AI & Machine Learning",
    academic: "Dr Manoj Kumar",
    mentors: ["AI/ML SME — GAP", "Sridas D — architecture focus", "Arun Nadh G — deployment and DevOps focus"],
  },
  CS102: {
    code: "CS102",
    title: "Full Stack Architecture & Cloud-Native Development",
    academic: "Dr Ajith Kumar",
    mentors: ["Sridas D", "Abhi Krishnan R", "Prasanth Lal S N", "Maneesh George Johnson", "Bibin Babu", "Arun Nadh G"],
    note: "Mentor disciplines cover architecture, frontend, mobile, full-stack and cloud delivery.",
  },
  CS501: {
    code: "CS501",
    title: "AI Ethics and Governance",
    academic: "Dr Manoj Kumar, Dr Ajith Kumar",
    mentors: ["Arun Kumar Balakrishnan — governance", "Nidheesh G — data privacy", "AI/ML SME — GAP — modelling ethics"],
  },
  CS601: {
    code: "CS601",
    title: "Advanced Frontend Frameworks",
    academic: "Dr Ajith Kumar",
    mentors: ["Abhi Krishnan R", "Prasanth Lal S N", "Maneesh George Johnson", "Bibin Babu — mobile"],
  },
};
